### ISSUE TITLE
Get input from speed log

### ISSUE THREAD

**Issue by billwallraff** [MarkAhlbrecht/DasBoot#1]
- [ ] Analyze log, need to connect scope to output
- [ ] Design circuit
- [ ] Build circuit
- [ ] Test circuit
- [ ] Pi integration
- [ ] AP integration

**Comment by billwallraff** [comment]
Mark, what is the speed log?  What is the interface? Do you have link to documentation or specs?

**Comment by MarkAhlbrecht** [comment]
The log measures the speed through water.  There is a little paddle wheel
that goes into the water and spins based on the water going past it.  I
think there is a maget on one of the paddles.  There is a pair of wires t
j.g at go to the display which is just an analog meter.  There is no power
other than that from the sensor.  I would like to digitize it and send it
to the pi.  All the components are up at the boat
