### ISSUE TITLE
Connect PI to Garmin

### ISSUE THREAD

**Issue by billwallraff** [MarkAhlbrecht/DasBoot#2]
- [x] Serial Loopback - general data
- [x] NMEA Decoder/Encoder (Open Source?)
- [x] loop back nmea data
- [x] PI to PI serial link
- [x] PI to PI NMEA
- [x] Garmin Rx

**Comment by billwallraff** [comment]
I will start working this task.  First a loop back test, then Pi to Pi serial link. Does Garmin have a NMEA serial I/O?

**Comment by MarkAhlbrecht** [comment]
It does.  Nmea is a text protocol that gets sent over 232 or 422.  Google
and you can see some examples.  I am guessing that the depth ($DPT) and GPS
($GGA) would be the ones we need.  Ill try to find out which exact model i
have
